### ISSUE TITLE
Tag `style` deve ser mapeada?

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/LMHT#8]
Usando um exemplo onde tem a tag style, não é gerado nada equivalente a `lmht`.

````html
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
    </style>
````
https://github.com/samuelrvg/delegua-blog

**Comment by leonelsanchesdasilva** [comment]
Esta é realmente uma exceção. `<estilo>` foi reservada para FolEs. Se eu não me engano, `<style>` é mantida como está, e usada para CSS.
